### PR TITLE
Added the Ātreyaśīkṣā

### PR DESCRIPTION
**Pull request by chakrabortydeepro**
Added the [Ātreyaśikṣā](https://www.panditproject.org/entity/109942/work) which I edited a few years ago from 2 manuscripts. There are two more Ātreyaśikṣās. I call this one Ātreyaśikṣā 3.

### CODE REVIEW

**Comment by drdhaval2785** [comment]
Namaste Deepro ji,
I have merged the text.

One request. 
I am not very frequently updating sanskritworld website.
Currently the following is the best place to contribute a work on github. https://github.com/sanskrit/raw_etexts

If you can create a pull request in appropriate folder, that would reach wider audience.

**Comment by chakrabortydeepro** [comment]
Namas te Dhaval ji,

Thanks for letting me know. I checked this repository. A version of this
text Ātreyaśīkṣā is already available there which is probably Peter
Freund's transcription of the Hamburg Codex. But my version is a product of
the critical edition. I am not sure if Visvas ji would be interested in
keeping two versions of the same text. But I can ask.

Thanks,
Deepro

**Comment by vvasuki** [comment]
@chakrabortydeepro - definitely interested to have various versions of identical texts. no objection whatsoever.

**Comment by chakrabortydeepro** [comment]
Thanks a lot Vishvas ji. I'll keep adding texts there.

**Pull request merged**
